context:
  version: 2023.9.30

package:
  name: psmamba
  version: '{{ version }}'

source:
  path: '.'

build:
  include_recipe: false
  number: 0
  script: python bld.py
  skip:
  - not win64
  - build_platform != target_platform

requirements:
  build:
  - "{{ compiler('cxx') }}"
  - python
  host:
  - libmamba 2
  run:
  - libmamba

about:
  home: https://github.com/snekdesign/PSMamba
  dev_url: https://github.com/snekdesign/PSMamba
  doc_url: https://github.com/snekdesign/PSMamba
  doc_source_url: https://github.com/snekdesign/PSMamba/blob/main/README.md
  license_file: LICENSE
  summary: PowerShell wrapper of libmamba
